### PR TITLE
Implemented GGN

### LINKED ISSUE #5: Implement GGN as an alternative Hessian approximation
### User story:
- User must be able to use all of the existing functionality with GGN (Generalised Gauss-Newton approximation)

### Subtasks:
- [x] Compute GGN approximation using Jacobians

### PR DESCRIPTION
**Pull request by navimakarov**
This merge request closes #5 

Implemented Generalized Gauss–Newton method (without support for mini-batching).  
Achieved the same predictions as python counterpart. 

Julia:
image

Python:
image

* Implemented test suite for GGN. 
* Added a test to Empirical Fisher.
* Set GGN as a default backend.

### CODE REVIEW

**Comment by Andrei32Ionescu** [comment]
Overall, this is great code, well documented and tested. If there is one thing I would try adding, it's a notebook showcasing the comparison between GGN and Fisher speeds and precisions, so that we can confirm our analytical assumptions. This is just a nitpick however, as I believe otherwise the code is ready to be merged.

**Review by Andrei32Ionescu — APPROVED** [review]

**Comment by navimakarov** [comment]
> Overall, this is great code, well documented and tested. If there is one thing I would try adding, it's a notebook showcasing the comparison between GGN and Fisher speeds and precisions, so that we can confirm our analytical assumptions. This is just a nitpick however, as I believe otherwise the code is ready to be merged.

That's a valid point, thanks! Will do so for the next sprint

**Comment by adelinacazacu** [comment]
Besides the point Andrei made, which I think is a good one to keep in mind for most of our notebooks in the future, this is very well-written code! I believe tests could be somewhat improved to be more extensive, but since we were already planning to have separate pull requests for improving test suites anyway, I say this is ready to be merged. Well done!

**Review by adelinacazacu — APPROVED** [review]
Besides the point Andrei made, which I think is a good one to keep in mind for most of our notebooks in the future, this is very well-written code! I believe tests could be somewhat improved to be more extensive, but since we were already planning to have separate pull requests for improving test suites anyway, I say this is ready to be merged. Well done!

**Pull request merged**
